export const keywords = [
    { word: "int", class: "DT" },
    { word: "float", class: "DT" },
    { word: "string", class: "DT" },
    { word: "short", class: "DT" },
    { word: "long", class: "DT" },
    { word: "double", class: "DT" },
    { word: "const", class: "const" },
    { word: "var", class: "DT" },
    { word: "bool", class: "DT" },


    { word: "while", class: "while" },
    { word: "do", class: "do" },
    { word: "for", class: "for" },
    { word: "if", class: "if" },
    { word: "else", class: "else" },
    { word: "switch", class: "switch" },
    { word: "case", class: "case" },
    { word: "return", class: "return" },
    { word: "break", class: "break" },
    { word: "continue", class: "continue" },
    { word: "true", class: "true" },
    { word: "false", class: "false" },
    { word: "class", class: "class" },
    { word: "protected", class: "protected" },
    { word: "static", class: "static" },
    { word: "Stack", class: "Stack" },
    { word: "Queue", class: "Queue" },
    { word: "ArrayList", class: "ArrayList" },
    { word: "function", class: "function" },
    { word: "Array", class: "Array" },
    { word: "Array2D", class: "Array2D" },
    { word: "print", class: "print" }
]