name: Node CI

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email "talibwaseem135@gmail.com"
        git config --global user.name "Muhammad Talib Waseem"
        git remote set-url origin https://MuhammadTalib:pak99haj@github.com/MuhammadTalib/Smart-Compiler.git
        npm run deploy